local M = {}

function M.build(c)
  local default_fg = c.fg_default or c.fg
  local normal_bg = c.bg
  local float_bg = c.bg_float
  local popup_bg = c.bg_popup
  local sidebar_bg = c.bg_sidebar
  local statusline_bg = c.bg_statusline
  local alt_bg = c.bg_alt

  return {
    Normal = { fg = default_fg, bg = normal_bg },
    NormalNC = { fg = default_fg, bg = normal_bg },
    NormalFloat = { fg = default_fg, bg = float_bg },
    FloatBorder = { fg = c.border, bg = float_bg },
    FloatTitle = { fg = c.accent, bg = float_bg, bold = true },
    ColorColumn = { bg = c.bg_subtle },
    CursorColumn = { bg = c.bg_cursorline },
    CursorLine = { bg = c.bg_cursorline },
    CursorLineNr = { fg = c.accent, bold = true },
    LineNr = { fg = c.fg_line_nr },
    SignColumn = { bg = normal_bg },
    VertSplit = { fg = c.border },
    WinSeparator = { fg = c.border },
    EndOfBuffer = { fg = c.bg_alt },
    FoldColumn = { fg = c.fg_muted, bg = alt_bg },
    Folded = { fg = c.fg_muted, bg = alt_bg },
    StatusLine = { fg = c.fg_ui, bg = statusline_bg },
    StatusLineNC = { fg = c.fg_muted, bg = statusline_bg },
    TabLine = { fg = c.fg_ui, bg = sidebar_bg },
    TabLineFill = { bg = sidebar_bg },
    TabLineSel = { fg = c.fg, bg = normal_bg, bold = true },
    Pmenu = { fg = c.fg, bg = popup_bg },
    PmenuSel = { fg = c.fg, bg = c.bg_subtle },
    PmenuSbar = { bg = c.bg_subtle },
    PmenuThumb = { bg = c.border },
    Visual = { bg = c.bg_visual },
    Search = { fg = c.fg, bg = c.bg_search },
    CurSearch = { fg = c.bg, bg = c.accent, bold = true },
    IncSearch = { fg = c.bg, bg = c.accent, bold = true },
    MatchParen = { fg = c.accent, bg = c.bg_cursorline, bold = true },
    Conceal = { fg = c.fg_muted },
    NonText = { fg = c.fg_muted },
    Whitespace = { fg = c.fg_muted },
    QuickFixLine = { bg = c.bg_subtle, bold = true },
    Directory = { fg = c.constant },
    Title = { fg = c.heading, bold = true },
    Underlined = { fg = c.link, underline = true },
    Question = { fg = c.info },
    MoreMsg = { fg = c.info },
    ModeMsg = { fg = c.accent },
    WarningMsg = { fg = c.warn },
    ErrorMsg = { fg = c.error },
    Error = { fg = c.error },
    Todo = { fg = c.heading, bold = true },
    Comment = { fg = c.fg_muted, italic = true },
    Constant = { fg = c.constant },
    String = { fg = c.string },
    Character = { fg = c.string },
    Number = { fg = c.number },
    Boolean = { fg = c.constant },
    Float = { fg = c.number },
    Identifier = { fg = c.fg_syntax },
    Function = { fg = c.func },
    Statement = { fg = c.keyword },
    Conditional = { fg = c.keyword },
    Repeat = { fg = c.keyword },
    Label = { fg = c.heading },
    Operator = { fg = c.keyword },
    Keyword = { fg = c.keyword },
    Exception = { fg = c.keyword },
    PreProc = { fg = c.keyword },
    Include = { fg = c.keyword },
    Define = { fg = c.keyword },
    Macro = { fg = c.keyword },
    PreCondit = { fg = c.keyword },
    Type = { fg = c.type },
    StorageClass = { fg = c.keyword },
    Structure = { fg = c.type },
    Typedef = { fg = c.type },
    Special = { fg = c.accent },
    SpecialChar = { fg = c.accent },
    Tag = { fg = c.tag },
    Delimiter = { fg = c.fg_punct },
    SpecialComment = { fg = c.fg_muted, italic = true },
    Debug = { fg = c.debug },
    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warn },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.string },
    DiagnosticSignError = { fg = c.error, bg = normal_bg },
    DiagnosticSignWarn = { fg = c.warn, bg = normal_bg },
    DiagnosticSignInfo = { fg = c.info, bg = normal_bg },
    DiagnosticSignHint = { fg = c.hint, bg = normal_bg },
    DiagnosticSignOk = { fg = c.string, bg = normal_bg },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.bg_subtle },
    DiagnosticVirtualTextWarn = { fg = c.warn, bg = c.bg_subtle },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.bg_subtle },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.bg_subtle },
    DiagnosticVirtualTextOk = { fg = c.string, bg = c.bg_subtle },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },
    DiagnosticUnderlineOk = { undercurl = true, sp = c.string },
    DiagnosticFloatingError = { fg = c.error, bg = float_bg },
    DiagnosticFloatingWarn = { fg = c.warn, bg = float_bg },
    DiagnosticFloatingInfo = { fg = c.info, bg = float_bg },
    DiagnosticFloatingHint = { fg = c.hint, bg = float_bg },
    DiagnosticFloatingOk = { fg = c.string, bg = float_bg },
    DiagnosticDeprecated = { fg = c.fg_muted, strikethrough = true },
    DiagnosticUnnecessary = { fg = c.fg_muted, italic = true },
    LspReferenceText = { bg = c.bg_subtle },
    LspReferenceRead = { bg = c.bg_subtle },
    LspReferenceWrite = { bg = c.bg_subtle, bold = true },
    LspInlayHint = { fg = c.fg_muted, bg = c.bg_alt, italic = true },
    LspCodeLens = { fg = c.fg_muted, italic = true },
    LspCodeLensSeparator = { fg = c.fg_muted },
    LspSignatureActiveParameter = { fg = c.parameter, underline = true, bold = true },
    LspInfoBorder = { fg = c.border, bg = float_bg },
    LspInfoTitle = { fg = c.accent, bold = true },
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { fg = c.fg, bg = c.bg_cursorline, bold = true },
    diffAdded = { fg = c.string },
    diffChanged = { fg = c.warn },
    diffRemoved = { fg = c.error },
    GitSignsAdd = { fg = c.string },
    GitSignsChange = { fg = c.warn },
    GitSignsDelete = { fg = c.error },
    CopilotSuggestion = { fg = c.fg_muted, italic = true },
    CopilotAnnotation = { fg = c.fg_muted, italic = true },
    CmpDocumentation = { fg = default_fg, bg = popup_bg },
    CmpDocumentationBorder = { fg = c.border, bg = popup_bg },
    CmpItemAbbr = { fg = default_fg },
    CmpItemAbbrDeprecated = { fg = c.fg_muted, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.constant, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.constant },
    CmpItemMenu = { fg = c.fg_muted },
    CmpItemKind = { fg = c.func },
    CmpItemKindVariable = { fg = c.fg_syntax },
    CmpItemKindFunction = { fg = c.func },
    CmpItemKindMethod = { fg = c.func },
    CmpItemKindClass = { fg = c.type },
    CmpItemKindInterface = { fg = c.type },
    CmpItemKindModule = { fg = c.type },
    CmpItemKindProperty = { fg = c.constant },
    CmpItemKindField = { fg = c.constant },
    CmpItemKindKeyword = { fg = c.keyword },
    CmpItemKindSnippet = { fg = c.string },
    CmpItemKindText = { fg = default_fg },
    BlinkCmpMenu = { fg = c.fg, bg = popup_bg },
    BlinkCmpMenuBorder = { fg = c.border, bg = popup_bg },
    BlinkCmpMenuSelection = { fg = c.fg, bg = c.bg_subtle },
    BlinkCmpScrollBarThumb = { bg = c.border },
    BlinkCmpScrollBarGutter = { bg = c.bg_subtle },
    BlinkCmpLabel = { link = "CmpItemAbbr" },
    BlinkCmpLabelDeprecated = { link = "CmpItemAbbrDeprecated" },
    BlinkCmpLabelMatch = { link = "CmpItemAbbrMatch" },
    BlinkCmpLabelDetail = { link = "CmpItemMenu" },
    BlinkCmpLabelDescription = { link = "CmpItemMenu" },
    BlinkCmpSource = { link = "CmpItemMenu" },
    BlinkCmpKind = { link = "CmpItemKind" },
    BlinkCmpKindText = { link = "CmpItemKindText" },
    BlinkCmpKindMethod = { link = "CmpItemKindMethod" },
    BlinkCmpKindFunction = { link = "CmpItemKindFunction" },
    BlinkCmpKindConstructor = { link = "CmpItemKindFunction" },
    BlinkCmpKindField = { link = "CmpItemKindField" },
    BlinkCmpKindVariable = { link = "CmpItemKindVariable" },
    BlinkCmpKindClass = { link = "CmpItemKindClass" },
    BlinkCmpKindInterface = { link = "CmpItemKindInterface" },
    BlinkCmpKindModule = { link = "CmpItemKindModule" },
    BlinkCmpKindProperty = { link = "CmpItemKindProperty" },
    BlinkCmpKindUnit = { link = "CmpItemKindText" },
    BlinkCmpKindValue = { link = "CmpItemKindText" },
    BlinkCmpKindEnum = { link = "CmpItemKindClass" },
    BlinkCmpKindKeyword = { link = "CmpItemKindKeyword" },
    BlinkCmpKindSnippet = { link = "CmpItemKindSnippet" },
    BlinkCmpKindColor = { link = "CmpItemKindText" },
    BlinkCmpKindFile = { link = "CmpItemKindText" },
    BlinkCmpKindReference = { link = "CmpItemKindVariable" },
    BlinkCmpKindFolder = { link = "CmpItemKindModule" },
    BlinkCmpKindEnumMember = { link = "CmpItemKindField" },
    BlinkCmpKindConstant = { link = "CmpItemKindField" },
    BlinkCmpKindStruct = { link = "CmpItemKindClass" },
    BlinkCmpKindEvent = { link = "CmpItemKindFunction" },
    BlinkCmpKindOperator = { link = "CmpItemKindKeyword" },
    BlinkCmpKindTypeParameter = { link = "CmpItemKindClass" },
    BlinkCmpGhostText = { fg = c.fg_muted, italic = true },
    BlinkCmpDoc = { fg = default_fg, bg = float_bg },
    BlinkCmpDocBorder = { fg = c.border, bg = float_bg },
    BlinkCmpDocSeparator = { fg = c.border, bg = float_bg },
    BlinkCmpDocCursorLine = { bg = c.bg_subtle },
    BlinkCmpSignatureHelp = { fg = default_fg, bg = float_bg },
    BlinkCmpSignatureHelpBorder = { fg = c.border, bg = float_bg },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
    SnacksNormal = { fg = default_fg, bg = float_bg },
    SnacksNormalNC = { fg = default_fg, bg = float_bg },
    SnacksTitle = { fg = c.accent, bg = float_bg, bold = true },
    SnacksFooter = { fg = default_fg, bg = float_bg },
    SnacksFooterDesc = { fg = c.info, bg = float_bg },
    SnacksFooterKey = { fg = c.info, bg = c.bg_subtle },
    SnacksWinBar = { fg = c.heading, bold = true },
    SnacksWinBarNC = { fg = c.fg_muted },
    SnacksWinSeparator = { fg = c.border },
    SnacksWinKey = { fg = c.keyword, bold = true },
    SnacksWinKeySep = { fg = c.fg_muted },
    SnacksWinKeyDesc = { fg = c.func },
    SnacksInputNormal = { fg = default_fg, bg = float_bg },
    SnacksInputBorder = { fg = c.info, bg = float_bg },
    SnacksInputTitle = { fg = c.info, bg = float_bg, bold = true },
    SnacksInputIcon = { fg = c.hint, bg = float_bg },
    SnacksNotifierHistory = { fg = default_fg, bg = float_bg },
    SnacksNotifierHistoryTitle = { fg = c.heading, bold = true },
    SnacksNotifierHistoryDateTime = { fg = c.accent },
    SnacksNotifierMinimal = { fg = default_fg, bg = float_bg },
    SnacksNotifierTrace = { fg = c.fg_muted, bg = float_bg },
    SnacksNotifierDebug = { fg = c.fg_muted, bg = float_bg },
    SnacksNotifierInfo = { fg = default_fg, bg = float_bg },
    SnacksNotifierWarn = { fg = default_fg, bg = float_bg },
    SnacksNotifierError = { fg = default_fg, bg = float_bg },
    SnacksNotifierIconTrace = { fg = c.fg_muted },
    SnacksNotifierIconDebug = { fg = c.fg_muted },
    SnacksNotifierIconInfo = { fg = c.info },
    SnacksNotifierIconWarn = { fg = c.warn },
    SnacksNotifierIconError = { fg = c.error },
    SnacksNotifierBorderTrace = { fg = c.fg_muted },
    SnacksNotifierBorderDebug = { fg = c.fg_muted },
    SnacksNotifierBorderInfo = { fg = c.info },
    SnacksNotifierBorderWarn = { fg = c.warn },
    SnacksNotifierBorderError = { fg = c.error },
    SnacksNotifierTitleTrace = { fg = c.fg_muted },
    SnacksNotifierTitleDebug = { fg = c.fg_muted },
    SnacksNotifierTitleInfo = { fg = c.info, bold = true },
    SnacksNotifierTitleWarn = { fg = c.warn, bold = true },
    SnacksNotifierTitleError = { fg = c.error, bold = true },
    SnacksNotifierFooterTrace = { fg = c.fg_muted },
    SnacksNotifierFooterDebug = { fg = c.fg_muted },
    SnacksNotifierFooterInfo = { fg = c.info },
    SnacksNotifierFooterWarn = { fg = c.warn },
    SnacksNotifierFooterError = { fg = c.error },
    SnacksDashboardNormal = { fg = default_fg, bg = normal_bg },
    SnacksDashboardIcon = { fg = c.accent },
    SnacksDashboardDesc = { fg = c.accent },
    SnacksDashboardKey = { fg = c.number, bold = true },
    SnacksDashboardHeader = { fg = c.heading, bold = true },
    SnacksDashboardFooter = { fg = c.heading, bold = true },
    SnacksDashboardTitle = { fg = c.heading, bold = true },
    SnacksDashboardSpecial = { fg = c.accent },
    SnacksDashboardFile = { fg = c.accent },
    SnacksDashboardDir = { fg = c.fg_muted },
    SnacksDashboardTerminal = { fg = default_fg, bg = normal_bg },
    SnacksIndent = { fg = c.bg_subtle },
    SnacksIndent1 = { fg = c.bg_subtle },
    SnacksIndent2 = { fg = c.bg_subtle },
    SnacksIndent3 = { fg = c.bg_subtle },
    SnacksIndent4 = { fg = c.bg_subtle },
    SnacksIndent5 = { fg = c.bg_subtle },
    SnacksIndent6 = { fg = c.bg_subtle },
    SnacksIndent7 = { fg = c.bg_subtle },
    SnacksIndent8 = { fg = c.bg_subtle },
    SnacksIndentScope = { fg = c.fg_line_nr },
    SnacksIndentChunk = { fg = c.fg_line_nr },
    SnacksPicker = { fg = default_fg, bg = float_bg },
    SnacksPickerBox = { fg = default_fg, bg = float_bg },
    SnacksPickerInput = { fg = default_fg, bg = popup_bg },
    SnacksPickerList = { fg = default_fg, bg = float_bg },
    SnacksPickerPreview = { fg = default_fg, bg = float_bg },
    SnacksPickerPrompt = { fg = c.accent, bold = true },
    SnacksPickerMatch = { fg = c.constant, bold = true },
    SnacksPickerSearch = { fg = c.bg, bg = c.accent, bold = true },
    SnacksPickerSpinner = { fg = c.accent },
    SnacksPickerTotals = { fg = c.fg_muted },
    SnacksPickerRule = { fg = c.fg_punct },
    SnacksPickerPickWin = { fg = c.bg, bg = c.bg_search },
    SnacksPickerPickWinCurrent = { fg = c.bg, bg = c.accent, bold = true },
    SnacksPickerSpecial = { fg = c.accent },
    SnacksPickerLabel = { fg = c.accent },
    SnacksPickerComment = { fg = c.fg_muted, italic = true },
    SnacksPickerDesc = { fg = c.fg_muted },
    SnacksPickerDelim = { fg = c.fg_punct },
    SnacksPickerDimmed = { fg = c.fg_muted },
    SnacksPickerFile = { fg = default_fg },
    SnacksPickerDirectory = { fg = c.constant },
    SnacksPickerDir = { fg = c.fg_muted },
    SnacksPickerPathIgnored = { fg = c.fg_muted },
    SnacksPickerPathHidden = { fg = c.fg_muted },
    SnacksPickerLink = { fg = c.fg_muted },
    SnacksPickerLinkBroken = { fg = c.error },
    SnacksPickerRow = { fg = c.string },
    SnacksPickerCol = { fg = c.fg_line_nr },
    SnacksPickerIdx = { fg = c.number },
    SnacksPickerCode = { fg = c.fg_alt },
    SnacksPickerItalic = { italic = true },
    SnacksPickerBold = { bold = true },
    SnacksPickerTree = { fg = c.fg_line_nr },
    SnacksPickerSelected = { fg = c.number },
    SnacksPickerUnselected = { fg = c.fg_muted },
    SnacksPickerCmd = { fg = c.func },
    SnacksPickerCmdBuiltin = { fg = c.func },
    SnacksPickerBufNr = { fg = c.number },
    SnacksPickerBufFlags = { fg = c.fg_muted },
    SnacksPickerBufType = { fg = c.func },
    SnacksPickerFileType = { fg = c.hint },
    SnacksPickerRegister = { fg = c.number },
    SnacksPickerKeymapMode = { fg = c.number },
    SnacksPickerKeymapLhs = { fg = c.accent },
    SnacksPickerKeymapNowait = { fg = c.constant },
    SnacksPickerKeymapRhs = { fg = c.fg_muted },
    SnacksPickerDiagnosticCode = { fg = c.accent },
    SnacksPickerDiagnosticSource = { fg = c.fg_muted },
    SnacksPickerNotificationMessage = { fg = default_fg },
    SnacksPickerGitStatus = { fg = c.accent },
    SnacksPickerGitStatusAdded = { fg = c.string },
    SnacksPickerGitStatusModified = { fg = c.warn },
    SnacksPickerGitStatusDeleted = { fg = c.error },
    SnacksPickerGitStatusRenamed = { fg = c.accent },
    SnacksPickerGitStatusCopied = { fg = c.accent },
    SnacksPickerGitStatusUntracked = { fg = c.fg_muted },
    SnacksPickerGitStatusIgnored = { fg = c.fg_muted },
    SnacksPickerGitStatusUnmerged = { fg = c.error },
    SnacksPickerGitStatusStaged = { fg = c.hint },
    SnacksPickerGitBranch = { fg = c.heading },
    SnacksPickerGitBranchCurrent = { fg = c.number, bold = true },
    SnacksPickerGitDetached = { fg = c.warn },
    SnacksPickerGitDate = { fg = c.accent },
    SnacksPickerGitIssue = { fg = c.number },
    SnacksPickerGitAuthor = { fg = c.constant },
    SnacksPickerGitType = { fg = c.heading },
    SnacksPickerGitScope = { fg = c.fg_syntax, italic = true },
    SnacksPickerGitCommit = { fg = c.constant },
    SnacksPickerGitBreaking = { fg = c.error, bold = true },
    SnacksPickerLspDisabled = { fg = c.warn },
    SnacksPickerLspEnabled = { fg = c.accent },
    SnacksPickerLspAttached = { fg = c.warn },
    SnacksPickerLspAttachedBuf = { fg = c.info },
    SnacksPickerLspUnavailable = { fg = c.error },
    SnacksPickerIcon = { fg = c.accent },
    SnacksPickerIconSource = { fg = c.constant },
    SnacksPickerIconName = { fg = c.keyword },
    SnacksPickerIconCategory = { fg = c.type },
    TelescopeNormal = { fg = default_fg, bg = float_bg },
    TelescopeBorder = { fg = c.border, bg = float_bg },
    TelescopePromptNormal = { fg = default_fg, bg = popup_bg },
    TelescopePromptBorder = { fg = c.border, bg = popup_bg },
    TelescopePromptTitle = { fg = c.bg, bg = c.accent, bold = true },
    TelescopePreviewTitle = { fg = c.bg, bg = c.constant, bold = true },
    TelescopeResultsTitle = { fg = c.bg, bg = c.heading, bold = true },
    TelescopeSelection = { bg = c.bg_subtle, bold = true },
    TelescopeMatching = { fg = c.constant, bold = true },
    TelescopePromptPrefix = { fg = c.accent },
    NvimTreeNormal = { fg = default_fg, bg = normal_bg },
    NvimTreeNormalNC = { fg = default_fg, bg = normal_bg },
    NvimTreeEndOfBuffer = { fg = normal_bg, bg = normal_bg },
    NvimTreeFolderName = { fg = c.constant },
    NvimTreeOpenedFolderName = { fg = c.constant, bold = true },
    NvimTreeRootFolder = { fg = c.heading, bold = true },
    NvimTreeSpecialFile = { fg = c.accent, underline = true },
    NvimTreeIndentMarker = { fg = c.fg_muted },
    NvimTreeImageFile = { fg = default_fg },
    NvimTreeSymlink = { fg = c.link },
    NvimTreeGitDirty = { fg = c.warn },
    NvimTreeGitNew = { fg = c.string },
    NvimTreeGitDeleted = { fg = c.error },
    NeoTreeNormal = { fg = default_fg, bg = normal_bg },
    NeoTreeNormalNC = { fg = default_fg, bg = normal_bg },
    NeoTreeEndOfBuffer = { fg = normal_bg, bg = normal_bg },
    NeoTreeFloatBorder = { fg = c.border, bg = float_bg },
    NeoTreeTitleBar = { fg = c.bg, bg = c.accent, bold = true },
    NeoTreeDirectoryName = { fg = c.constant },
    NeoTreeDirectoryIcon = { fg = c.constant },
    NeoTreeRootName = { fg = c.heading, bold = true },
    NeoTreeIndentMarker = { fg = c.fg_muted },
    NeoTreeGitAdded = { fg = c.string },
    NeoTreeGitModified = { fg = c.warn },
    NeoTreeGitDeleted = { fg = c.error },
    NeoTreeGitConflict = { fg = c.error, bold = true },
    NeoTreeGitUntracked = { fg = c.info },
    WhichKey = { fg = c.constant, bold = true },
    WhichKeyGroup = { fg = c.heading },
    WhichKeyDesc = { fg = default_fg },
    WhichKeySeparator = { fg = c.fg_muted },
    WhichKeyValue = { fg = c.fg_muted },
    WhichKeyBorder = { fg = c.border, bg = float_bg },
    WhichKeyFloat = { fg = default_fg, bg = float_bg },
    TroubleNormal = { fg = default_fg, bg = normal_bg },
    TroubleNormalNC = { fg = default_fg, bg = normal_bg },
    TroubleText = { fg = default_fg },
    TroubleCount = { fg = c.bg, bg = c.accent, bold = true },
    TroubleIndent = { fg = c.fg_muted },
    TroubleCode = { fg = c.constant },
    TroubleFoldIcon = { fg = c.fg_muted },
    TroubleError = { fg = c.error },
    TroubleWarn = { fg = c.warn },
    TroubleInfo = { fg = c.info },
    TroubleHint = { fg = c.hint },
    IblIndent = { fg = c.bg_subtle },
    IblScope = { fg = c.fg_line_nr },
    IndentBlanklineChar = { fg = c.bg_subtle },
    IndentBlanklineContextChar = { fg = c.fg_line_nr },
    ["@annotation"] = { fg = c.constant },
    ["@attribute"] = { fg = c.constant },
    ["@attribute.builtin"] = { fg = c.constant },
    ["@boolean"] = { fg = c.constant },
    ["@character"] = { fg = c.string },
    ["@character.special"] = { fg = c.accent },
    ["@comment"] = { fg = c.fg_muted, italic = true },
    ["@comment.documentation"] = { fg = c.fg_muted, italic = true },
    ["@comment.error"] = { fg = c.error, bold = true },
    ["@comment.todo"] = { fg = c.heading, bold = true },
    ["@comment.warning"] = { fg = c.warn, bold = true },
    ["@constant"] = { fg = c.constant },
    ["@constant.builtin"] = { fg = c.constant },
    ["@constant.macro"] = { fg = c.keyword },
    ["@constructor"] = { fg = c.func },
    ["@diff.delta"] = { fg = c.warn },
    ["@diff.minus"] = { fg = c.error },
    ["@diff.plus"] = { fg = c.string },
    ["@function"] = { fg = c.func },
    ["@function.builtin"] = { fg = c.func },
    ["@function.call"] = { fg = c.func },
    ["@function.macro"] = { fg = c.keyword },
    ["@function.method"] = { fg = c.func },
    ["@function.method.call"] = { fg = c.func },
    ["@keyword"] = { fg = c.keyword },
    ["@keyword.conditional"] = { fg = c.keyword },
    ["@keyword.conditional.ternary"] = { fg = c.keyword },
    ["@keyword.debug"] = { fg = c.debug },
    ["@keyword.directive"] = { fg = c.keyword },
    ["@keyword.directive.define"] = { fg = c.keyword },
    ["@keyword.exception"] = { fg = c.keyword },
    ["@keyword.function"] = { fg = c.keyword },
    ["@keyword.import"] = { fg = c.keyword },
    ["@keyword.modifier"] = { fg = c.keyword },
    ["@keyword.operator"] = { fg = c.keyword },
    ["@keyword.repeat"] = { fg = c.keyword },
    ["@keyword.return"] = { fg = c.keyword },
    ["@keyword.type"] = { fg = c.keyword },
    ["@label"] = { fg = c.heading },
    ["@markup"] = { fg = default_fg },
    ["@markup.heading"] = { fg = c.heading, bold = true },
    ["@markup.heading.1"] = { fg = c.heading, bold = true },
    ["@markup.heading.2"] = { fg = c.heading, bold = true },
    ["@markup.heading.3"] = { fg = c.heading, bold = true },
    ["@markup.heading.4"] = { fg = c.heading, bold = true },
    ["@markup.heading.5"] = { fg = c.heading, bold = true },
    ["@markup.heading.6"] = { fg = c.heading, bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.link, underline = true },
    ["@markup.link.label"] = { fg = c.markdown_link_text },
    ["@markup.link.url"] = { fg = c.link, underline = true },
    ["@markup.list"] = { fg = c.heading },
    ["@markup.list.checked"] = { fg = c.string },
    ["@markup.list.unchecked"] = { fg = c.fg_muted },
    ["@markup.math"] = { fg = c.constant },
    ["@markup.quote"] = { fg = c.fg_muted, italic = true },
    ["@markup.raw"] = { fg = c.fg_alt },
    ["@markup.raw.block"] = { fg = c.fg_alt },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { fg = c.heading, bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { fg = c.type },
    ["@module.builtin"] = { fg = c.type },
    ["@number"] = { fg = c.number },
    ["@number.float"] = { fg = c.number },
    ["@operator"] = { fg = c.keyword },
    ["@property"] = { fg = c.constant },
    ["@punctuation.bracket"] = { fg = c.fg_punct },
    ["@punctuation.delimiter"] = { fg = c.fg_punct },
    ["@punctuation.special"] = { fg = c.fg_punct },
    ["@string"] = { fg = c.string },
    ["@string.documentation"] = { fg = c.fg_alt },
    ["@string.escape"] = { fg = c.accent },
    ["@string.regexp"] = { fg = c.string },
    ["@string.special"] = { fg = c.constant },
    ["@string.special.path"] = { fg = c.constant },
    ["@string.special.symbol"] = { fg = c.constant },
    ["@string.special.url"] = { fg = c.link, underline = true },
    ["@tag"] = { fg = c.tag },
    ["@tag.attribute"] = { fg = c.constant },
    ["@tag.delimiter"] = { fg = c.fg_punct },
    ["@type"] = { fg = c.type },
    ["@type.builtin"] = { fg = c.type },
    ["@type.definition"] = { fg = c.type },
    ["@variable"] = { fg = c.fg_syntax },
    ["@variable.builtin"] = { fg = c.constant },
    ["@variable.member"] = { fg = c.constant },
    ["@variable.parameter"] = { fg = c.parameter },
    ["@lsp.type.boolean"] = { link = "@boolean" },
    ["@lsp.type.builtinType"] = { link = "@type.builtin" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
    ["@lsp.type.event"] = { link = "@type" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@type" },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.modifier"] = { link = "@keyword.modifier" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.regexp"] = { link = "@string.regexp" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    TSAnnotation = { link = "@annotation" },
    TSAttribute = { link = "@attribute" },
    TSBoolean = { link = "@boolean" },
    TSCharacter = { link = "@character" },
    TSComment = { link = "@comment" },
    TSConditional = { link = "@keyword.conditional" },
    TSConstant = { link = "@constant" },
    TSConstBuiltin = { link = "@constant.builtin" },
    TSConstMacro = { link = "@constant.macro" },
    TSConstructor = { link = "@constructor" },
    TSError = { link = "@comment.error" },
    TSException = { link = "@keyword.exception" },
    TSField = { link = "@property" },
    TSFloat = { link = "@number.float" },
    TSFunction = { link = "@function" },
    TSFuncBuiltin = { link = "@function.builtin" },
    TSFuncMacro = { link = "@function.macro" },
    TSInclude = { link = "@keyword.import" },
    TSKeyword = { link = "@keyword" },
    TSKeywordFunction = { link = "@keyword.function" },
    TSKeywordOperator = { link = "@keyword.operator" },
    TSLabel = { link = "@label" },
    TSMethod = { link = "@function.method" },
    TSNamespace = { link = "@module" },
    TSNumber = { link = "@number" },
    TSOperator = { link = "@operator" },
    TSParameter = { link = "@variable.parameter" },
    TSProperty = { link = "@property" },
    TSPunctDelimiter = { link = "@punctuation.delimiter" },
    TSPunctBracket = { link = "@punctuation.bracket" },
    TSPunctSpecial = { link = "@punctuation.special" },
    TSRepeat = { link = "@keyword.repeat" },
    TSString = { link = "@string" },
    TSStringEscape = { link = "@string.escape" },
    TSStringRegex = { link = "@string.regexp" },
    TSStrong = { link = "@markup.strong" },
    TSTag = { link = "@tag" },
    TSTagDelimiter = { link = "@tag.delimiter" },
    TSText = { link = "Normal" },
    TSTitle = { link = "@markup.heading" },
    TSType = { link = "@type" },
    TSTypeBuiltin = { link = "@type.builtin" },
    TSURI = { link = "@markup.link.url" },
    TSVariable = { link = "@variable" },
    TSVariableBuiltin = { link = "@variable.builtin" },
    markdownText = { fg = default_fg },
    markdownBold = { fg = c.heading, bold = true },
    markdownItalic = { italic = true },
    markdownH1 = { fg = c.heading, bold = true },
    markdownH2 = { fg = c.heading, bold = true },
    markdownH3 = { fg = c.heading, bold = true },
    markdownH4 = { fg = c.heading, bold = true },
    markdownH5 = { fg = c.heading, bold = true },
    markdownH6 = { fg = c.heading, bold = true },
    markdownHeadingDelimiter = { fg = c.heading, bold = true },
    markdownCode = { fg = c.fg_alt },
    markdownCodeBlock = { fg = c.fg_alt },
    markdownCodeDelimiter = { fg = c.markdown_link_text },
    markdownUrl = { fg = c.link, underline = true },
    markdownLinkText = { fg = c.markdown_link_text },
    markdownLinkDelimiter = { fg = c.markdown_bracket },
    markdownLinkTextDelimiter = { fg = c.markdown_bracket },
    markdownListMarker = { fg = c.heading },
    markdownOrderedListMarker = { fg = c.heading },
    markdownRule = { fg = c.fg_muted },
  }
end

return M
